apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-service
  namespace: {{ .Values.namespace }}
  labels:
    app: messages-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: messages-service
  template:
    metadata:
      labels:
        app: messages-service
    spec:
      containers:
        - name: messages-service
          image: "{{ .Values.images.messages.repository }}:{{ .Values.images.messages.tag }}"
          imagePullPolicy: {{ .Values.images.messages.pullPolicy }}
          ports:
            - containerPort: {{ .Values.messagesService.port }}
          env:
            - name: PORT
              value: "{{ .Values.messagesService.port }}"
