apiVersion: v1
kind: Service
metadata:
  name: messages-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: messages-service
  ports:
    - port: {{ .Values.messagesService.port }}
      targetPort: {{ .Values.messagesService.port }}
