apiVersion: v1
kind: Service
metadata:
  name: family-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: family-service
  ports:
    - port: {{ .Values.familyService.port }}
      targetPort: {{ .Values.familyService.port }}
